---
- hosts: all
  roles:
  - prometheus.prometheus.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - "{{ target_node }}:9100"
        labels:
          env: demosite

    prometheus_alertmanager_config:
    - static_configs:
      - targets: 
        - localhost:9093